name: Docker-Compose and unit testing
on: push
jobs:
  Docker-Compose-up-and-run-pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker containers
        run: docker-compose up -d
      - name: Run unit tests
        run: docker-compose exec -T fastapi-app python -m pytest